-- ==================================================================
-- Poolepedia - Fish index
-- Pre-built reverse lookup: fishName -> sorted list of zones/pools
-- where that fish can be caught.
--
-- Generated from PoolepediaDB.lua + PoolepediaZones.lua.
-- Update this file when new expansion content is added.
--
-- Each entry: { zoneID, zoneName, poolName }
-- Entries whithin each fish are sorted alphabetically by zoneName
-- ==================================================================

PoolepediaFishIndex = {
    -- Classic --------------------------------------
    ["Raw Brilliant Smallfish"] = {
        { zoneID = 1, zoneName = "Durotar", poolName = "Open-Water"},
	    { zoneID = 7, zoneName = "Mulgore", poolName = "Open-Water"},
        { zoneID = 10, zoneName = "Northern Barrens", poolName = "Open-Water"},
        { zoneID = 18, zoneName = "Tirisfal Glades", poolName = "Open-Water"},
        { zoneID = 21, zoneName = "Silverpine Forest", poolName = "Open-Water"},
        { zoneID = 27, zoneName = "Dun Morogh", poolName = "Open-Water"},
        { zoneID = 30, zoneName = "New Tinkertown", poolName = "Open-Water"},
	    { zoneID = 37, zoneName = "Elwynn Forest", poolName = "Open-Water"},
        { zoneID = 47, zoneName = "Duskwood", poolName = "Open-Water"},
	    { zoneID = 48, zoneName = "Loch Modan", poolName = "Open-Water"},
        { zoneID = 49, zoneName = "Redridge Mountains", poolName = "Open-Water"},
        { zoneID = 52, zoneName = "Westfall", poolName = "Open-Water"},
	    { zoneID = 55, zoneName = "The Deadmines", poolName = "Open-Water"},
	    { zoneID = 57, zoneName = "Teldrassil", poolName = "Open-Water"},
	    { zoneID = 62, zoneName = "Darkshore", poolName = "Open-Water"},
        { zoneID = 63, zoneName = "Ashenvale", poolName = "Open-Water"},
	    { zoneID = 76, zoneName = "Azshara", poolName = "Open-Water"},
        { zoneID = 84, zoneName = "Stormwind City", poolName = "Open-Water"},
	    { zoneID = 85, zoneName = "Orgrimmar", poolName = "Open-Water"},
	    { zoneID = 87, zoneName = "Ironforge", poolName = "Open-Water"},
	    { zoneID = 88, zoneName = "Thunder Bluff", poolName = "Open-Water"},
        { zoneID = 89, zoneName = "Darnassus", poolName = "Open-Water"},
	    { zoneID = 90, zoneName = "Undercity", poolName = "Open-Water"},
        { zoneID = 94, zoneName = "Eversong Woods (BC)", poolName = "Open-Water"},
        { zoneID = 95, zoneName = "Ghostlands", poolName = "Open-Water"},
        { zoneID = 97, zoneName = "Azuremyst Isle", poolName = "Open-Water"},
	    { zoneID = 221, zoneName = "Blackfathom Deeps", poolName = "Open-Water"},
        { zoneID = 425, zoneName = "Northshire", poolName = "Open-Water"},
        { zoneID = 461, zoneName = "Valley of trials", poolName = "Open-Water"},
        { zoneID = 462, zoneName = "Camp Narache", poolName = "Open-Water"},
        { zoneID = 463, zoneName = "Echo Isles", poolName = "Open-Water"},
        { zoneID = 468, zoneName = "Ammen Vale", poolName = "Open-Water"},
    },
    ["Raw Longjaw Mud Snapper"] = {
        { zoneID = 1, zoneName = "Durotar", poolName = "Open-Water"},
	    { zoneID = 7, zoneName = "Mulgore", poolName = "Open-Water"},
        { zoneID = 10, zoneName = "Northern Barrens", poolName = "Open-Water"},
        { zoneID = 14, zoneName = "Arathi Highlands", poolName = "Open-Water"},
        { zoneID = 18, zoneName = "Tirisfal Glades", poolName = "Open-Water"},
        { zoneID = 21, zoneName = "Silverpine Forest", poolName = "Open-Water"},
        { zoneID = 25, zoneName = "Hillsbrad Foothills", poolName = "Open-Water"},
        { zoneID = 27, zoneName = "Dun Morogh", poolName = "Open-Water"},
        { zoneID = 30, zoneName = "New Tinkertown", poolName = "Open-Water"},
	    { zoneID = 37, zoneName = "Elwynn Forest", poolName = "Open-Water"},
        { zoneID = 47, zoneName = "Duskwood", poolName = "Open-Water"},
	    { zoneID = 48, zoneName = "Loch Modan", poolName = "Open-Water"},
        { zoneID = 49, zoneName = "Redridge Mountains", poolName = "Open-Water"},
	    { zoneID = 50, zoneName = "Northern Stranglethorn", poolName = "Open-Water"},
        { zoneID = 52, zoneName = "Westfall", poolName = "Open-Water"},
        { zoneID = 56, zoneName = "Wetlands", poolName = "Open-Water"},
	    { zoneID = 57, zoneName = "Teldrassil", poolName = "Open-Water"},
	    { zoneID = 62, zoneName = "Darkshore", poolName = "Open-Water"},
        { zoneID = 63, zoneName = "Ashenvale", poolName = "Open-Water"},
        { zoneID = 65, zoneName = "Stonetalon Mountains", poolName = "Open-Water"},
	    { zoneID = 76, zoneName = "Azshara", poolName = "Open-Water"},
        { zoneID = 84, zoneName = "Stormwind City", poolName = "Open-Water"},
	    { zoneID = 85, zoneName = "Orgrimmar", poolName = "Open-Water"},
	    { zoneID = 87, zoneName = "Ironforge", poolName = "Open-Water"},
	    { zoneID = 88, zoneName = "Thunder Bluff", poolName = "Open-Water"},
        { zoneID = 89, zoneName = "Darnassus", poolName = "Open-Water"},
	    { zoneID = 90, zoneName = "Undercity", poolName = "Open-Water"},
        { zoneID = 94, zoneName = "Eversong Woods (BC)", poolName = "Open-Water"},
        { zoneID = 95, zoneName = "Ghostlands", poolName = "Open-Water"},
        { zoneID = 425, zoneName = "Northshire", poolName = "Open-Water"},
        { zoneID = 463, zoneName = "Echo Isles", poolName = "Open-Water"},
        { zoneID = 468, zoneName = "Ammen Vale", poolName = "Open-Water"},
    },
    ["Raw Slitherskin Mackerel"] = {
        { zoneID = 1, zoneName = "Durotar", poolName = "Open-Water"},
        { zoneID = 10, zoneName = "Northern Barrens", poolName = "Open-Water"},
        { zoneID = 13, zoneName = "Ruins of Gilneas", poolName = "Open-Water"},
        { zoneID = 18, zoneName = "Tirisfal Glades", poolName = "Open-Water"},
        { zoneID = 21, zoneName = "Silverpine Forest", poolName = "Open-Water"},
        { zoneID = 27, zoneName = "Dun Morogh", poolName = "Open-Water"},
        { zoneID = 52, zoneName = "Westfall", poolName = "Open-Water"},
	    { zoneID = 57, zoneName = "Teldrassil", poolName = "Open-Water"},
	    { zoneID = 62, zoneName = "Darkshore", poolName = "Open-Water"},
	    { zoneID = 76, zoneName = "Azshara", poolName = "Open-Water"},
        { zoneID = 84, zoneName = "Stormwind City", poolName = "Open-Water"},
        { zoneID = 94, zoneName = "Eversong Woods (BC)", poolName = "Open-Water"},
        { zoneID = 95, zoneName = "Ghostlands", poolName = "Open-Water"},
        { zoneID = 97, zoneName = "Azuremyst Isle", poolName = "Open-Water"},
	    { zoneID = 103, zoneName = "The Exodar", poolName = "Open-Water"},
        { zoneID = 106, zoneName = "Bloodmyst Isle", poolName = "Open-Water"},
        { zoneID = 174, zoneName = "The Lost Isles", poolName = "Open-Water"},
        { zoneID = 179, zoneName = "Gilneas", poolName = "Open-Water"},
        { zoneID = 199, zoneName = "Southern Barrens", poolName = "Open-Water"},
	    { zoneID = 407, zoneName = "Darkmoon Island", poolName = "Open-Water"},
        { zoneID = 463, zoneName = "Echo Isles", poolName = "Open-Water"},
	    { zoneID = 467, zoneName = "Sunstrider Isle", poolName = "Open-Water"},
    },
    ["Sickly Looking Fish"] = {
        { zoneID = 18, zoneName = "Tirisfal Glades", poolName = "Open-Water"},
        { zoneID = 21, zoneName = "Silverpine Forest", poolName = "Open-Water"},
	    { zoneID = 62, zoneName = "Darkshore", poolName = "Open-Water"},
	    { zoneID = 90, zoneName = "Undercity", poolName = "Open-Water"},
	    { zoneID = 221, zoneName = "Blackfathom Deeps", poolName = "Open-Water"},
    },
    ["Raw Bristle Whisker Catfish"] = {
        { zoneID = 10, zoneName = "Northern Barrens", poolName = "Open-Water"},       
        { zoneID = 14, zoneName = "Arathi Highlands", poolName = "Open-Water"},
        { zoneID = 21, zoneName = "Silverpine Forest", poolName = "Open-Water"},
        { zoneID = 22, zoneName = "Western Plaguelands", poolName = "Open-Water"},
        { zoneID = 23, zoneName = "Eastern Plaguelands", poolName = "Open-Water"},
        { zoneID = 25, zoneName = "Hillsbrad Foothills", poolName = "Open-Water"},
        { zoneID = 26, zoneName = "The Hinterlands", poolName = "Open-Water"},
        { zoneID = 27, zoneName = "Dun Morogh", poolName = "Open-Water"},
	    { zoneID = 37, zoneName = "Elwynn Forest", poolName = "Open-Water"},
        { zoneID = 47, zoneName = "Duskwood", poolName = "Open-Water"},
	    { zoneID = 48, zoneName = "Loch Modan", poolName = "Open-Water"},
        { zoneID = 49, zoneName = "Redridge Mountains", poolName = "Open-Water"},
	    { zoneID = 50, zoneName = "Northern Stranglethorn", poolName = "Open-Water"},
        { zoneID = 51, zoneName = "Swamp of Sorrows", poolName = "Open-Water"},
        { zoneID = 52, zoneName = "Westfall", poolName = "Open-Water"},
	    { zoneID = 55, zoneName = "The Deadmines", poolName = "Open-Water"},
        { zoneID = 56, zoneName = "Wetlands", poolName = "Open-Water"},
	    { zoneID = 62, zoneName = "Darkshore", poolName = "Open-Water"},
        { zoneID = 63, zoneName = "Ashenvale", poolName = "Open-Water"},
        { zoneID = 65, zoneName = "Stonetalon Mountains", poolName = "Open-Water"},
        { zoneID = 66, zoneName = "Desolace", poolName = "Open-Water"},
        { zoneID = 69, zoneName = "Feralas", poolName = "Open-Water"},
        { zoneID = 70, zoneName = "Dustwallow Marsh", poolName = "Open-Water"},
	    { zoneID = 76, zoneName = "Azshara", poolName = "Open-Water"},
        { zoneID = 84, zoneName = "Stormwind City", poolName = "Open-Water"},
	    { zoneID = 85, zoneName = "Orgrimmar", poolName = "Open-Water"},
	    { zoneID = 87, zoneName = "Ironforge", poolName = "Open-Water"},
	    { zoneID = 88, zoneName = "Thunder Bluff", poolName = "Open-Water"},
        { zoneID = 89, zoneName = "Darnassus", poolName = "Open-Water"},
	    { zoneID = 90, zoneName = "Undercity", poolName = "Open-Water"},
        { zoneID = 94, zoneName = "Eversong Woods (BC)", poolName = "Open-Water"},
        { zoneID = 95, zoneName = "Ghostlands", poolName = "Open-Water"},
        { zoneID = 199, zoneName = "Southern Barrens", poolName = "Open-Water"},
	    { zoneID = 210, zoneName = "The Cape of Stranglethorn", poolName = "Open-Water"},
	    { zoneID = 221, zoneName = "Blackfathom Deeps", poolName = "Open-Water"},
        { zoneID = 224, zoneName = "Stranglethorn Vale", poolName = "Open-Water"},
    },
    ["Raw Mithril Head Trout"] = {
        { zoneID = 14, zoneName = "Arathi Highlands", poolName = "Open-Water"},
        { zoneID = 15, zoneName = "Badlands", poolName = "Open-Water"},
        { zoneID = 22, zoneName = "Western Plaguelands", poolName = "Open-Water"},
        { zoneID = 23, zoneName = "Eastern Plaguelands", poolName = "Open-Water"},
        { zoneID = 25, zoneName = "Hillsbrad Foothills", poolName = "Open-Water"},
        { zoneID = 26, zoneName = "The Hinterlands", poolName = "Open-Water"},
        { zoneID = 51, zoneName = "Swamp of Sorrows", poolName = "Open-Water"},
        { zoneID = 66, zoneName = "Desolace", poolName = "Open-Water"},
        { zoneID = 67, zoneName = "Maraudon", poolName = "Open-Water"},
        { zoneID = 69, zoneName = "Feralas", poolName = "Open-Water"},
        { zoneID = 70, zoneName = "Dustwallow Marsh", poolName = "Open-Water"},
        { zoneID = 71, zoneName = "Tanaris", poolName = "Open-Water"},
        { zoneID = 77, zoneName = "Felwood", poolName = "Open-Water"},
        { zoneID = 80, zoneName = "Moonglade", poolName = "Open-Water"},
        { zoneID = 199, zoneName = "Southern Barrens", poolName = "Open-Water"},
	    { zoneID = 210, zoneName = "The Cape of Stranglethorn", poolName = "Open-Water"},
	    { zoneID = 219, zoneName = "Zul'Farak", poolName = "Open-Water"},
        { zoneID = 224, zoneName = "Stranglethorn Vale", poolName = "Open-Water"}
    },
    ["Raw Glossy Mightfish"] = {        
        { zoneID = 15, zoneName = "Badlands", poolName = "Open-Water"},
        { zoneID = 23, zoneName = "Eastern Plaguelands", poolName = "Open-Water"},
        { zoneID = 26, zoneName = "The Hinterlands", poolName = "Open-Water"},
	    { zoneID = 50, zoneName = "Northern Stranglethorn", poolName = "Open-Water"},
        { zoneID = 64, zoneName = "Thousand Needles", poolName = "Open-Water"},
        { zoneID = 69, zoneName = "Feralas", poolName = "Open-Water"},
        { zoneID = 71, zoneName = "Tanaris", poolName = "Open-Water"},
	    { zoneID = 76, zoneName = "Azshara", poolName = "Open-Water"},
	    { zoneID = 210, zoneName = "The Cape of Stranglethorn", poolName = "Open-Water"},
        { zoneID = 224, zoneName = "Stranglethorn Vale", poolName = "Open-Water"},
	    { zoneID = 407, zoneName = "Darkmoon Island", poolName = "Open-Water"},
    },
    ["Oily Blackmouth"] = {
        { zoneID = 10, zoneName = "Northern Barrens", poolName = "Oily Blackmouth School"},
        { zoneID = 13, zoneName = "Ruins of Gilneas", poolName = "Oily Blackmouth School"},
        { zoneID = 14, zoneName = "Arathi Highlands", poolName = "Oily Blackmouth School"},
        { zoneID = 15, zoneName = "Badlands", poolName = "Oily Blackmouth School"},
        { zoneID = 17, zoneName = "Blasted Lands", poolName = "Oily Blackmouth School"},
        { zoneID = 18, zoneName = "Tirisfal Glades", poolName = "Oily Blackmouth School"},
        { zoneID = 21, zoneName = "Silverpine Forest", poolName = "Oily Blackmouth School"},
        { zoneID = 22, zoneName = "Western Plaguelands", poolName = "Oily Blackmouth School"},
        { zoneID = 23, zoneName = "Eastern Plaguelands", poolName = "Oily Blackmouth School"},
        { zoneID = 25, zoneName = "Hillsbrad Foothills", poolName = "Oily Blackmouth School"},
        { zoneID = 26, zoneName = "The Hinterlands", poolName = "Oily Blackmouth School"},
        { zoneID = 27, zoneName = "Dun Morogh", poolName = "Oily Blackmouth School"},
	    { zoneID = 50, zoneName = "Northern Stranglethorn", poolName = "Oily Blackmouth School"},
        { zoneID = 51, zoneName = "Swamp of Sorrows", poolName = "Oily Blackmouth School"},
        { zoneID = 52, zoneName = "Westfall", poolName = "Oily Blackmouth School"},
        { zoneID = 56, zoneName = "Wetlands", poolName = "Oily Blackmouth School"},
	    { zoneID = 62, zoneName = "Darkshore", poolName = "Oily Blackmouth School"},
        { zoneID = 63, zoneName = "Ashenvale", poolName = "Oily Blackmouth School"},
        { zoneID = 64, zoneName = "Thousand Needles", poolName = "Oily Blackmouth School"},
        { zoneID = 65, zoneName = "Stonetalon Mountains", poolName = "Oily Blackmouth School"},
        { zoneID = 66, zoneName = "Desolace", poolName = "Oily Blackmouth School"},
        { zoneID = 67, zoneName = "Maraudon", poolName = "Oily Blackmouth School"},
        { zoneID = 69, zoneName = "Feralas", poolName = "Oily Blackmouth School"},
        { zoneID = 70, zoneName = "Dustwallow Marsh", poolName = "Oily Blackmouth School"},
        { zoneID = 71, zoneName = "Tanaris", poolName = "Oily Blackmouth School"},
	    { zoneID = 76, zoneName = "Azshara", poolName = "Oily Blackmouth School"},
        { zoneID = 77, zoneName = "Felwood", poolName = "Oily Blackmouth School"},
        { zoneID = 80, zoneName = "Moonglade", poolName = "Oily Blackmouth School"},
        { zoneID = 84, zoneName = "Stormwind City", poolName = "Oily Blackmouth School"},
        { zoneID = 95, zoneName = "Ghostlands", poolName = "Oily Blackmouth School"},
        { zoneID = 97, zoneName = "Azuremyst Isle", poolName = "Oily Blackmouth School"},
        { zoneID = 106, zoneName = "Bloodmyst Isle", poolName = "Oily Blackmouth School"},
        { zoneID = 111, zoneName = "Wetlands", poolName = "Oily Blackmouth School"},
        { zoneID = 199, zoneName = "Southern Barrens", poolName = "Oily Blackmouth School"},
	    { zoneID = 210, zoneName = "The Cape of Stranglethorn", poolName = "Oily Blackmouth School"},
        { zoneID = 224, zoneName = "Stranglethorn Vale", poolName = "Oily Blackmouth School"},
        { zoneID = 241, zoneName = "Twilight Highlands", poolName = "Oily Blackmouth School"},
	    { zoneID = 407, zoneName = "Darkmoon Island", poolName = "Oily Blackmouth School"},
    },
    ["Firefin Snapper"] = {
        { zoneID = 10, zoneName = "Northern Barrens", poolName = "Firefin Snapper School"},
        { zoneID = 14, zoneName = "Arathi Highlands", poolName = "Firefin Snapper School"},
        { zoneID = 15, zoneName = "Badlands", poolName = "Firefin Snapper School"},
        { zoneID = 17, zoneName = "Blasted Lands", poolName = "Firefin Snapper School"},
        { zoneID = 18, zoneName = "Tirisfal Glades", poolName = "Firefin Snapper School"},
        { zoneID = 21, zoneName = "Silverpine Forest", poolName = "Firefin Snapper School"},
        { zoneID = 23, zoneName = "Eastern Plaguelands", poolName = "Firefin Snapper School"},
        { zoneID = 25, zoneName = "Hillsbrad Foothills", poolName = "Firefin Snapper School"},
        { zoneID = 26, zoneName = "The Hinterlands", poolName = "Firefin Snapper School"},
	    { zoneID = 50, zoneName = "Northern Stranglethorn", poolName = "Firefin Snapper School"},
        { zoneID = 50, zoneName = "Northern Stranglethorn", poolName = "Mixed Ocean School"},
        { zoneID = 51, zoneName = "Swamp of Sorrows", poolName = "Firefin Snapper School"},
        { zoneID = 52, zoneName = "Westfall", poolName = "Firefin Snapper School"},
        { zoneID = 56, zoneName = "Wetlands", poolName = "Firefin Snapper School"},
	    { zoneID = 62, zoneName = "Darkshore", poolName = "Firefin Snapper School"},
        { zoneID = 63, zoneName = "Ashenvale", poolName = "Firefin Snapper School"},
        { zoneID = 64, zoneName = "Thousand Needles", poolName = "Firefin Snapper School"},
        { zoneID = 65, zoneName = "Stonetalon Mountains", poolName = "Firefin Snapper School"},
        { zoneID = 66, zoneName = "Desolace", poolName = "Firefin Snapper School"},
        { zoneID = 69, zoneName = "Feralas", poolName = "Firefin Snapper School"},
        { zoneID = 70, zoneName = "Dustwallow Marsh", poolName = "Firefin Snapper School"},
        { zoneID = 71, zoneName = "Tanaris", poolName = "Firefin Snapper School"},
        { zoneID = 76, zoneName = "Azshara", poolName = "Firefin Snapper School"},
        { zoneID = 199, zoneName = "Southern Barrens", poolName = "Firefin Snapper School"},
        { zoneID = 210, zoneName = "The Cape of Stranglethorn", poolName = "Firefin Snapper School"},
        { zoneID = 210, zoneName = "The Cape of Stranglethorn", poolName = "Mixed Ocean School"},
        { zoneID = 224, zoneName = "Stranglethorn Vale", poolName = "Firefin Snapper School"},
        { zoneID = 241, zoneName = "Twilight Highlands", poolName = "Firefin Snapper School"},
	    { zoneID = 407, zoneName = "Darkmoon Island", poolName = "Firefin Snapper School"},
    },
    ["Stonescale Eel"] = {
        { zoneID = 15, zoneName = "Badlands", poolName = "Stonescale Eel Swarm"},
        { zoneID = 17, zoneName = "Blasted Lands", poolName = "Stonescale Eel Swarm"},
        { zoneID = 23, zoneName = "Eastern Plaguelands", poolName = "Stonescale Eel Swarm"},
        { zoneID = 26, zoneName = "The Hinterlands", poolName = "Stonescale Eel Swarm"},
        { zoneID = 27, zoneName = "Dun Morogh", poolName = "Stonescale Eel Swarm"},
	    { zoneID = 50, zoneName = "Northern Stranglethorn", poolName = "Stonescale Eel Swarm"},
        { zoneID = 51, zoneName = "Swamp of Sorrows", poolName = "Stonescale Eel Swarm"},
        { zoneID = 64, zoneName = "Thousand Needles", poolName = "Stonescale Eel Swarm"},
        { zoneID = 69, zoneName = "Feralas", poolName = "Stonescale Eel Swarm"},
        { zoneID = 71, zoneName = "Tanaris", poolName = "Stonescale Eel Swarm"},
        { zoneID = 76, zoneName = "Azshara", poolName = "Stonescale Eel Swarm"},
        { zoneID = 210, zoneName = "The Cape of Stranglethorn", poolName = "Stonescale Eel Swarm"},
        { zoneID = 224, zoneName = "Stranglethorn Vale", poolName = "Stonescale Eel Swarm"},
	    { zoneID = 407, zoneName = "Darkmoon Island", poolName = "Stonescale Eel Swarm"},
    },
    ["Raw Sagefish"] = {
        { zoneID = 1, zoneName = "Durotar", poolName = "Sagefish School"},
        { zoneID = 10, zoneName = "Northern Barrens", poolName = "Sagefish School"},
        { zoneID = 18, zoneName = "Tirisfal Glades", poolName = "Sagefish School"},
        { zoneID = 21, zoneName = "Silverpine Forest", poolName = "Sagefish School"},
        { zoneID = 25, zoneName = "Hillsbrad Foothills", poolName = "Sagefish School"},
        { zoneID = 27, zoneName = "Dun Morogh", poolName = "Sagefish School"},
	    { zoneID = 37, zoneName = "Elwynn Forest", poolName = "Sagefish School"},
        { zoneID = 47, zoneName = "Duskwood", poolName = "Sagefish School"},
	    { zoneID = 48, zoneName = "Loch Modan", poolName = "Sagefish School"},
        { zoneID = 49, zoneName = "Redridge Mountains", poolName = "Sagefish School"},
	    { zoneID = 50, zoneName = "Northern Stranglethorn", poolName = "Sagefish School"},
        { zoneID = 52, zoneName = "Westfall", poolName = "Sagefish School"},
        { zoneID = 56, zoneName = "Wetlands", poolName = "Sagefish School"},
	    { zoneID = 62, zoneName = "Darkshore", poolName = "Sagefish School"},
        { zoneID = 63, zoneName = "Ashenvale", poolName = "Sagefish School"},
        { zoneID = 65, zoneName = "Stonetalon Mountains", poolName = "Sagefish School"},
        { zoneID = 76, zoneName = "Azshara", poolName = "Sagefish School"},
        { zoneID = 210, zoneName = "The Cape of Stranglethorn", poolName = "Sagefish School"},
    },
    ["Raw Greater Sagefish"] = {
        { zoneID = 14, zoneName = "Arathi Highlands", poolName = "Greater Sagefish School"},
        { zoneID = 17, zoneName = "Blasted Lands", poolName = "Greater Sagefish School"},
        { zoneID = 22, zoneName = "Western Plaguelands", poolName = "Greater Sagefish School"},
        { zoneID = 23, zoneName = "Eastern Plaguelands", poolName = "Greater Sagefish School"},
        { zoneID = 25, zoneName = "Hillsbrad Foothills", poolName = "Greater Sagefish School"},
        { zoneID = 26, zoneName = "The Hinterlands", poolName = "Greater Sagefish School"},
        { zoneID = 27, zoneName = "Dun Morogh", poolName = "Greater Sagefish School"},
	    { zoneID = 50, zoneName = "Northern Stranglethorn", poolName = "Greater Sagefish School"},
        { zoneID = 64, zoneName = "Thousand Needles", poolName = "Greater Sagefish School"},
        { zoneID = 65, zoneName = "Stonetalon Mountains", poolName = "Greater Sagefish School"},
        { zoneID = 66, zoneName = "Desolace", poolName = "Greater Sagefish School"},
        { zoneID = 69, zoneName = "Feralas", poolName = "Greater Sagefish School"},
        { zoneID = 70, zoneName = "Dustwallow Marsh", poolName = "Greater Sagefish School"},
        { zoneID = 78, zoneName = "Un'Goro Crater", poolName = "Greater Sagefish School"},
        { zoneID = 80, zoneName = "Moonglade", poolName = "Greater Sagefish School"},
        { zoneID = 210, zoneName = "The Cape of Stranglethorn", poolName = "Greater Sagefish School"},
        { zoneID = 224, zoneName = "Stranglethorn Vale", poolName = "Greater Sagefish School"},
    },
    ["Deviate Fish"] = {
        { zoneID = 71, zoneName = "Tanaris", poolName = "School of Deviate Fish"},
        { zoneID = 84, zoneName = "Stormwind City", poolName = "School of Deviate Fish"},
        { zoneID = 85, zoneName = "Orgrimmar", poolName = "School of Deviate Fish"}
    },

    -- The Burning Crusade ---------------------------
    ["Golden Darter"] = {
        { zoneID = 104, zoneName = "Blade's Edge Mountains", poolName = "Golden Darter School"},
        { zoneID = 107, zoneName = "Nagrand", poolName = "Golden Darter School"},
        { zoneID = 108, zoneName = "Terokkar Forest", poolName = "Golden Darter School"},
    },
    ["Zangarian Sporefish"] = {
        { zoneID = 119, zoneName = "Zangarmarsh", poolName = "Sporefish School"},
    },
    ["Spotted Feltail"] = {
        { zoneID = 119, zoneName = "Zangarmarsh", poolName = "Brackish Mixed School"},
        { zoneID = 119, zoneName = "Zangarmarsh", poolName = "Mudfish School"},
    },
    ["Figluster's Mudfish"] = {
        { zoneID = 104, zoneName = "Blade's Edge Mountains", poolName = "Highland Mixed School"},
        { zoneID = 119, zoneName = "Zangarmarsh", poolName = "Mudfish School"},
    },
    ["Icefin Bluefish"] = {
        { zoneID = 104, zoneName = "Blade's Edge Mountains", poolName = "Highland Mixed School"},
    },
    ["Huge Bluefish"] = {
        { zoneID = 109, zoneName = "Netherstorm", poolName = "Bluefish School"},
    },
    ["Purified Draenic Water"] = {
        { zoneID = 106, zoneName = "Shadowmoon Valley", poolName = "School of Pure Water"},
        { zoneID = 109, zoneName = "Netherstorm", poolName = "School of Pure Water"},
    },
    ["Barbed Gill Trout"] = {
        { zoneID = 104, zoneName = "Blade's Edge Mountains", poolName = "Barbed Gill Trout School"},
        { zoneID = 106, zoneName = "Shadowmoon Valley", poolName = "Barbed Gill Trout School"},
        { zoneID = 107, zoneName = "Nagrand", poolName = "Barbed Gill Trout School"},
        { zoneID = 108, zoneName = "Terokkar Forest", poolName = "Barbed Gill Trout School"},
        { zoneID = 119, zoneName = "Zangarmarsh", poolName = "Barbed Gill Trout School"},
    },
    ["Naga Hide"] = {
        { zoneID = 119, zoneName = "Zangarmarsh", poolName = "Naga Hide School"},
    },

    -- Wrath of the Lich King -----------------------
    ["Dragonfin Angelfish"] = {
        { zoneID = 120, zoneName = "Scholazar Basin", poolName = "Dragonfin Angelfish School"},
    },
    ["Fangtooth Herring"] = {
        { zoneID = 114, zoneName = "Grizzly Hills", poolName = "Fangtooth Herring School"},
        { zoneID = 116, zoneName = "Howling Fjord", poolName = "Fangtooth Herring School"},
    },
    ["Imperial Manta Ray"] = {
        { zoneID = 117, zoneName = "Borean Tundra", poolName = "Imperial Manta Ray School"},
        { zoneID = 121, zoneName = "Icecrown", poolName = "Imperial Manta Ray School"},
    },
    ["Moonglow Cuttlefish"] = {
        { zoneID = 115, zoneName = "Dragonblight", poolName = "Moonglow Cuttlefish School"},
        { zoneID = 116, zoneName = "Howling Fjord", poolName = "Moonglow Cuttlefish School"},
    },
    ["Musselback Sculpin"] = {
        { zoneID = 115, zoneName = "Dragonblight", poolName = "Musselback Sculpin School"},
        { zoneID = 117, zoneName = "Borean Tundra", poolName = "Musselback Sculpin School"},
    },
    ["Nettlefish"] = {
        { zoneID = 113, zoneName = "Zul'Drak", poolName = "Nettlefish School"},
        { zoneID = 114, zoneName = "Grizzly Hills", poolName = "Nettlefish School"},
        { zoneID = 120, zoneName = "Scholazar Basin", poolName = "Nettlefish School"},
    },
    ["Glacial Salmon"] = {
        { zoneID = 113, zoneName = "Zul'Drak", poolName = "Glacial Salmon School"},
        { zoneID = 114, zoneName = "Grizzly Hills", poolName = "Glacial Salmon School"},
        { zoneID = 118, zoneName = "Storm Peaks", poolName = "Glacial Salmon School"},
    },
    ["Deep Sea Monsterbelly"] = {
        { zoneID = 117, zoneName = "Borean Tundra", poolName = "Deep Sea Monsterbelly School"},
        { zoneID = 121, zoneName = "Icecrown", poolName = "Deep Sea Monsterbelly School"},
    },
    ["Borean Man O' War"] = {
        { zoneID = 117, zoneName = "Borean Tundra", poolName = "Borean Man O' War School"},
    },
    ["Glassfin Minnow"] = {
        { zoneID = 115, zoneName = "Dragonblight", poolName = "Glassfin Minnow School"},
        { zoneID = 116, zoneName = "Howling Fjord", poolName = "Glassfin Minnow School"},
        { zoneID = 118, zoneName = "Storm Peaks", poolName = "Glassfin Minnow School"},
        { zoneID = 125, zoneName = "Dalaran (Northrend)", poolName = "Glassfin Minnow School"},
    },

    -- Cataclysm -----------------------------------
    ["Algaefin Rockfish"] = {
        { zoneID = 198, zoneName = "Mount Hyjal", poolName = "Algaefin Rockfish School"},
        { zoneID = 207, zoneName = "Deepholm", poolName = "Algaefin Rockfish School"},
        { zoneID = 241, zoneName = "Twilight Highlands", poolName = "Algaefin Rockfish School"},
    },
    ["Deepsea Sagefish"] = {
        { zoneID = 207, zoneName = "Deepholm", poolName = "Deepsea Sagefish School"},
        { zoneID = 249, zoneName = "Uldum", poolName = "Deepsea Sagefish School"},
    },
    ["Fathom Eel"] = {
        { zoneID = 203, zoneName = "Vashj'ir - Kelp'thar Forest", poolName = "Fathom Eel School"},
        { zoneID = 204, zoneName = "Vashj'ir - Shimmering Expanse", poolName = "Fathom Eel School"},
        { zoneID = 205, zoneName = "Vashj'ir - Abyssal Depths", poolName = "Fathom Eel School"},
        { zoneID = 241, zoneName = "Twilight Highlands", poolName = "Shipwreck Debris"},
    },
    ["Highland Guppy"] = {
        { zoneID = 241, zoneName = "Twilight Highlands", poolName = "Highland Guppy School"},
        { zoneID = 249, zoneName = "Uldum", poolName = "Highland Guppy School"},
    },
    ["Lavascale Catfish"] = {
        { zoneID = 198, zoneName = "Mount Hyjal", poolName = "Lavascale Catfish School"},
        { zoneID = 249, zoneName = "Uldum", poolName = "Lavascale Catfish School"},
    },
    ["Murglesnout"] = {
        { zoneID = 203, zoneName = "Vashj'ir - Kelp'thar Forest", poolName = "Murglesnout School"},
        { zoneID = 204, zoneName = "Vashj'ir - Shimmering Expanse", poolName = "Murglesnout School"},
        { zoneID = 205, zoneName = "Vashj'ir - Abyssal Depths", poolName = "Murglesnout School"},
    },
    ["Striped Lurker"] = {
        { zoneID = 241, zoneName = "Twilight Highlands", poolName = "Striped Lurker School"},
    },

    -- Mists of Pandaria --------------------------
    ["Jewel Danio"] = {
        { zoneID = 371, zoneName = "The Jade Forest", poolName = "Jewel Danio School"},
        { zoneID = 390, zoneName = "Vale of Eternal Blossoms", poolName = "Jewel Danio School"},
    },
    ["Krasarang Paddlefish"] = {
        { zoneID = 371, zoneName = "The Jade Forest", poolName = "Krasarang Paddlefish School"},
        { zoneID = 379, zoneName = "Krasarang Wilds", poolName = "Krasarang Paddlefish School"},
    },
    ["Giant Mantis Shrimp"] = {
        { zoneID = 376, zoneName = "Valley of the Four Winds", poolName = "Giant Mantis Shrimp School"},
        { zoneID = 384, zoneName = "Dread Wastes", poolName = "Giant Mantis Shrimp School"},
        { zoneID = 388, zoneName = "Townlong Steppes", poolName = "Giant Mantis Shrimp School"},
    },
    ["Emperor Salmon"] = {
        { zoneID = 376, zoneName = "Valley of the Four Winds", poolName = "Emperor Salmon School"},
        { zoneID = 379, zoneName = "Krasarang Wilds", poolName = "Emperor Salmon School"},
        { zoneID = 381, zoneName = "Kun-Lai Summit", poolName = "Emperor Salmon School"},
    },
    ["Tiger Gourami"] = {
        { zoneID = 376, zoneName = "Valley of the Four Winds", poolName = "Tiger Gourami School"},
        { zoneID = 388, zoneName = "Townlong Steppes", poolName = "Tiger Gourami School"},
    },
    ["Reef Octopus"] = {
        { zoneID = 371, zoneName = "The Jade Forest", poolName = "Reef Octopus School"},
        { zoneID = 384, zoneName = "Dread Wastes", poolName = "Reef Octopus School"},
        { zoneID = 390, zoneName = "Vale of Eternal Blossoms", poolName = "Reef Octopus School"},
    },
    ["Spinefish Alpha"] = {
        { zoneID = 381, zoneName = "Kun-Lai Summit", poolName = "Spinefish School"},
    },

    -- Warlords of Draenor -------------------------
    ["Abyssal Gulper Eel"] = {
        { zoneID = 542, zoneName = "Spires of Arak", poolName = "Abyssal Gulper Eel School"},
        { zoneID = 572, zoneName = "Tanaan Jungle", poolName = "Abyssal Gulper Eel School"},
    },
    ["Blind Lake Sturgeon"] = {
        { zoneID = 525, zoneName = "Frostfire Ridge", poolName = "Blind Lake Sturgeon School"},
        { zoneID = 539, zoneName = "Shadowmoon Valley (Draenor)", poolName = "Blind Lake Sturgeon School"},
        { zoneID = 550, zoneName = "Nagrand (Draenor)", poolName = "Blind Lake Sturgeon School"},
        { zoneID = 535, zoneName = "Talador", poolName = "Blind Lake Sturgeon School"},
    },
    ["Crescent Saberfish"] = {
        { zoneID = 535, zoneName = "Talador", poolName = "Crescent Saberfish School"},
        { zoneID = 542, zoneName = "Spires of Arak", poolName = "Crescent Saberfish School"},
        { zoneID = 543, zoneName = "Gorgrond", poolName = "Crescent Saberfish School"},
    },
    ["Fat Sleeper"] = {
        { zoneID = 543, zoneName = "Gorgrond", poolName = "Fat Sleeper School"},
        { zoneID = 550, zoneName = "Nagrand (Draenor)", poolName = "Fat Sleeper School"},
    },
    ["Jawless Skulker"] = {
        { zoneID = 525, zoneName = "Frostfire Ridge", poolName = "Jawless Skulker School"},
        { zoneID = 535, zoneName = "Talador", poolName = "Jawless Skulker School"},
        { zoneID = 539, zoneName = "Shadowmoon Valley (Draenor)", poolName = "Jawless Skulker School"},
        { zoneID = 550, zoneName = "Nagrand (Draenor)", poolName = "Jawless Skulker School"},
    },
    ["Fire Ammonite Tentacle"] = {
        { zoneID = 542, zoneName = "Spires of Arak", poolName = "Fire Ammonite School"},
        { zoneID = 572, zoneName = "Tanaan Jungle", poolName = "Fire Ammonite School"},
    },

    -- Legion ----------------------------------------
    ["Cursed Queenfish"] = {
        { zoneID = 630, zoneName = "Azsuna", poolName = "Cursed Queenfish School"},
        { zoneID = 650, zoneName = "Stormheim", poolName = "Cursed Queenfish School"},
    },
    ["Highmountain Salmon"] = {
        { zoneID = 634, zoneName = "Highmountain", poolName = "Highmountain Salmon School"},
    },
    ["Mossgill Perch"] = {
        { zoneID = 634, zoneName = "Highmountain", poolName = "Mossgill Perch School"},
        { zoneID = 641, zoneName = "Val'sharah", poolName = "Mossgill Perch School"},
        { zoneID = 680, zoneName = "Suramar", poolName = "Mossgill Perch School"},
    },
    ["Runescale Koi"] = {
        { zoneID = 634, zoneName = "Highmountain", poolName = "Runescale Koi School"},
        { zoneID = 641, zoneName = "Val'sharah", poolName = "Runescale Koi School"},
        { zoneID = 680, zoneName = "Suramar", poolName = "Runescale Koi School"},
    },
    ["Stormray"] = {
        { zoneID = 630, zoneName = "Azsuna", poolName = "Stormray School"},
        { zoneID = 650, zoneName = "Stormheim", poolName = "Stormray School"},
    },
    ["Black Barracuda"] = {
        { zoneID = 630, zoneName = "Azsuna", poolName = "Black Barracuda School"},
        { zoneID = 650, zoneName = "Stormheim", poolName = "Black Barracuda School"},
        { zoneID = 680, zoneName = "Suramar", poolName = "Black Barracuda School"},
    },

    -- Battle for Azeroth --------------------------
    ["Tiragarde Perch"] = {
        { zoneID = 895, zoneName = "Tiragarde Sound", poolName = "Tiragarde Perch School"},
        { zoneID = 896, zoneName = "Drustvar", poolName = "Tiragarde Perch School"},
        { zoneID = 1462, zoneName = "Mechagon Island", poolName = "Tiragarde Perch School"},
    },
    ["Frenzied Fangtooth"] = {
        { zoneID = 895, zoneName = "Tiragarde Sound", poolName = "Frenzied Fangtooth School"},
        { zoneID = 896, zoneName = "Drustvar", poolName = "Frenzied Fangtooth School"},
        { zoneID = 942, zoneName = "Stormsong Valley", poolName = "Frenzied Fangtooth School"},
        { zoneID = 1355, zoneName = "Nazjatar", poolName = "Frenzied Fangtooth School"},
        { zoneID = 1462, zoneName = "Mechagon Island", poolName = "Frenzied Fangtooth School"},
    },
    ["Lane Snapper"] = {
        { zoneID = 895, zoneName = "Tiragarde Sound", poolName = "Lane Snapper School"},
        { zoneID = 942, zoneName = "Stormsong Valley", poolName = "Lane Snapper School"},
        { zoneID = 1355, zoneName = "Nazjatar", poolName = "Lane Snapper School"},
    },
    ["Redtail Loach"] = {
        { zoneID = 862, zoneName = "Zuldazar", poolName = "Redtail Loach School"},
        { zoneID = 863, zoneName = "Nazmir", poolName = "Redtail Loach School"},
    },
    ["Sand Shifter"] = {
        { zoneID = 862, zoneName = "Zuldazar", poolName = "Sand Shifter School"},
        { zoneID = 864, zoneName = "Vol'dun", poolName = "Sand Shifter School"},
    },
    ["Slimy Mackerel"] = {
        { zoneID = 895, zoneName = "Tiragarde Sound", poolName = "Slimy Mackerel School"},
        { zoneID = 942, zoneName = "Stormsong Valley", poolName = "Slimy Mackerel School"},
        { zoneID = 1355, zoneName = "Nazjatar", poolName = "Slimy Mackerel School"},
    },
    ["Midnight Salmon"] = {
        { zoneID = 862, zoneName = "Zuldazar", poolName = "Midnight Salmon School"},
        { zoneID = 863, zoneName = "Nazmir", poolName = "Midnight Salmon School"},
        { zoneID = 864, zoneName = "Vol'dun", poolName = "Midnight Salmon School"},
    },

    -- Shadowlands ---------------------------------
    ["Elysian Thade"] = {
        { zoneID = 1533, zoneName = "Bastion", poolName = "Elysian Thade School"},
        { zoneID = 1970, zoneName = "Zereth Mortis", poolName = "Elysian Thade School"},
    },
    ["Lost Sole"] = {
        { zoneID = 1565, zoneName = "Ardenweald", poolName = "Lost Sole School"},
        { zoneID = 1970, zoneName = "Zereth Mortis", poolName = "Lost Sole School"},
    },
    ["Silvergill Pike"] = {
        { zoneID = 1533, zoneName = "Bastion", poolName = "Silvergill Pike School"},
        { zoneID = 1565, zoneName = "Ardenweald", poolName = "Silvergill Pike School"},
    },
    ["Spinefin Piranha"] = {
        { zoneID = 1536, zoneName = "Maldraxxus", poolName = "Spinefin Piranha School"},
        { zoneID = 1543, zoneName = "The Maw", poolName = "Spinefin Piranha School"},
    },
    ["Pocked Bonefish"] = {
        { zoneID = 1525, zoneName = "Revendreth", poolName = "Pocked Bonefish School"},
        { zoneID = 1536, zoneName = "Maldraxxus", poolName = "Pocked Bonefish School"},
    },
    ["Iridescent Amberjack"] = {
        { zoneID = 1525, zoneName = "Revendreth", poolName = "Iridescent Amberjack School"},
        { zoneID = 1961, zoneName = "Korthia", poolName = "Iridescent Amberjack School"},
    },

    -- Dragonflight --------------------------------
    ["Aileron Seamoth"] = {
        { zoneID = 2022, zoneName = "The Waking Shores", poolName = "Aileron Seamoth School"},
        { zoneID = 2024, zoneName = "The Azure Span", poolName = "Aileron Seamoth School"},
        { zoneID = 2112, zoneName = "The Forbidden Reach", poolName = "Aileron Seamoth School"},
        { zoneID = 2133, zoneName = "Zaralek Cavern", poolName = "Aileron Seamoth School"},
    },
    ["Cerulean Spinefish"] = {
        { zoneID = 2022, zoneName = "The Waking Shores", poolName = "Cerulean Spinefish School"},
        { zoneID = 2023, zoneName = "Ohn'ahran Plains", poolName = "Cerulean Spinefish School"},
        { zoneID = 2024, zoneName = "The Azure Span", poolName = "Cerulean Spinefish School"},
        { zoneID = 2112, zoneName = "The Forbidden Reach", poolName = "Cerulean Spinefish School"},
    },
    ["Temporal Dragonhead"] = {
        { zoneID = 2022, zoneName = "The Waking Shores", poolName = "Temporal Dragonhead School"},
        { zoneID = 2025, zoneName = "Thaldraszus", poolName = "Temporal Dragonhead School"},
    },
    ["Islefin Dorado"] = {
        { zoneID = 2023, zoneName = "Ohn'ahran Plains", poolName = "Islefin Dorado School"},
        { zoneID = 2025, zoneName = "Thaldraszus", poolName = "Islefin Dorado School"},
        { zoneID = 2133, zoneName = "Zaralek Cavern", poolName = "Islefin Dorado School"},
        { zoneID = 2200, zoneName = "Emerald Dream", poolName = "Islefin Dorado School"},
    },
    ["Thousandbite Piranha"] = {
        { zoneID = 2024, zoneName = "The Azure Span", poolName = "Thousandbite Piranha School"},
    },
    ["Scalebelly Mackerel"] = {
        { zoneID = 2024, zoneName = "The Azure Span", poolName = "Scalebelly Mackerel School"},
        { zoneID = 2025, zoneName = "Thaldraszus", poolName = "Scalebelly Mackerel School"},
    },
    ["Prismatic Leaper"] = {
        { zoneID = 2023, zoneName = "Ohn'ahran Plains", poolName = "Prismatic Leaper School"},
        { zoneID = 2200, zoneName = "Emerald Dream", poolName = "Prismatic Leaper School"},
    },

    -- The War Within  ----------------------------
    ["Bismuth Bitterling"] = {
        { zoneID = 2214, zoneName = "The Ringing Deeps ", poolName = "Glimmerpool"},
        { zoneID = 2215, zoneName = "Hallowfall", poolName = "Glimmerpool"},
        { zoneID = 2248, zoneName = "Isle of Dorn", poolName = "Glimmerpool"},
        { zoneID = 2255, zoneName = "Azj-Kahet ", poolName = "Glimmerpool"},
        { zoneID = 2277, zoneName = "Nightfall Sanctum", poolName = "Glimmerpool"},
        { zoneID = 2339, zoneName = "Dornogal", poolName = "Glimmerpool"},
        { zoneID = 2346, zoneName = "Undermine", poolName = "Glimmerpool"},
        { zoneID = 2351, zoneName = "Razorwind Shores", poolName = "Glimmerpool"},
        { zoneID = 2352, zoneName = "Founder's Point", poolName = "Glimmerpool"},
        { zoneID = 2369, zoneName = "Siren Isle", poolName = "Glimmerpool"},
    },
    ["Bloody Perch"] = {
        
        { zoneID = 2371, zoneName = "K'aresh", poolName = ""},
    },

    -- Midnight  ----------------------------
    ["Arcane Wyrmfish"] = {
        { zoneID = 2395, zoneName = "Eversong Woods", poolName = "Bubbling Bloom, Sunwell Swarm"},
        { zoneID = 2413, zoneName = "Harandar", poolName = "Blossoming Torrent"},
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Open-Water"},
        { zoneID = 2505, zoneName = "The Gulf of Memory", poolName = "Open-Water"},
        { zoneID = 2535, zoneName = "Atal'Aman", poolName = "Open-Water"},
        { zoneID = 2565, zoneName = "Isle of Quel'Danas", poolName = "Open-Water"},
    },
    ["Lynxfish"] = {
        { zoneID = 2393, zoneName = "Silvermoon City", poolName = "Open-Water"},
        { zoneID = 2395, zoneName = "Eversong", poolName = "Bubbling Bloom, Sunwell Swarm"},
        { zoneID = 2413, zoneName = "Harandar", poolName = "Open-Water"},
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Surface Ripple"},
        { zoneID = 2505, zoneName = "The Gulf of Memory", poolName = "Open-Water"},
        { zoneID = 2535, zoneName = "Atal'Aman", poolName = "Open-Water"},
        { zoneID = 2536, zoneName = "Atal'Aman", poolName = "Open-Water"},
        { zoneID = 2565, zoneName = "Isle of Quel'Danas", poolName = "Open-Water"},
    },
    ["Root Crab"] = {
        { zoneID = 2413, zoneName = "Harandar", poolName = "Open-Water"},
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Obscured School, Surface Ripple"},
        { zoneID = 2505, zoneName = "The Gulf of Memory", poolName = "Open-Water"},
        { zoneID = 2535, zoneName = "Atal'Aman", poolName = "Open-Water"},
        { zoneID = 2536, zoneName = "Atal'Aman", poolName = "Open-Water"},
    },
    ["Sin'dorei Swarmer"] = {
        { zoneID = 2393, zoneName = "Silvermoon City", poolName = "Open-Water"},
        { zoneID = 2395, zoneName = "Eversong Woods", poolName = "Open-Water"},
        { zoneID = 2413, zoneName = "Harandar", poolName = "Bubbling Bloom, Sunwell Swarm, Surface Ripple"},
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Open-Water"},
        { zoneID = 2505, zoneName = "The Gulf of Memory", poolName = "Open-Water"},
        { zoneID = 2535, zoneName = "Atal'Aman", poolName = "Open-Water"},
        { zoneID = 2536, zoneName = "Atal'Aman", poolName = "Open-Water"},
        { zoneID = 2565, zoneName = "Isle of Quel'Danas", poolName = "Open-Water"},
    },
    ["Blood Hunter"] = {
        { zoneID = 2395, zoneName = "Eversong Woods", poolName = "Viscous Void"},
        { zoneID = 2405, zoneName = "Voidstorm", poolName = "Oceanic Vortex"},
        { zoneID = 2413, zoneName = "Harandar", poolName = "Viscous Void"},
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Surface Ripple, Hunter Surge, Viscous Void"},
        { zoneID = 2535, zoneName = "Atal'Aman", poolName = "Open-Water"},
        { zoneID = 2536, zoneName = "Atal'Aman", poolName = "Open-Water"},
    },
    ["Bloomtail Minnow"] = {
        { zoneID = 2413, zoneName = "Harandar", poolName = "Lashing Waves"},
        { zoneID = 2505, zoneName = "The Gulf of Memory", poolName = "Open-Water"},
    },
    ["Shimmer Spinefish"] = {
        { zoneID = 2393, zoneName = "Silvermoon City", poolName = "Open-Water"},
        { zoneID = 2395, zoneName = "Eversong Woods", poolName = "Bloom Swarm, Bubbling Bloom, Sunwell Swarm"},
        { zoneID = 2413, zoneName = "Harandar", poolName = "Blossoming Torrent"},
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Open-Water"},
        { zoneID = 2505, zoneName = "The Gulf of Memory", poolName = "Open-Water"},
        { zoneID = 2536, zoneName = "Atal'Aman", poolName = "Open-Water"},
        { zoneID = 2565, zoneName = "Isle of Quel'Danas", poolName = "Open-Water"},
    },
    ["Fungalskin Pike"] = {
        { zoneID = 2413, zoneName = "Harandar", poolName = "Lashing Waves"},
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Obscured School, Surface Ripple"},
        { zoneID = 2505, zoneName = "The Gulf of Memory", poolName = "Open-Water"},
        { zoneID = 2535, zoneName = "Atal'Aman", poolName = "Open-Water"},
        { zoneID = 2536, zoneName = "Atal'Aman", poolName = "Open-Water"},
    },
    ["Gore Guppy"] = {
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Surface Ripple, Hunter Surge"},
        { zoneID = 2535, zoneName = "Atal'Aman", poolName = "Open-Water"},
        { zoneID = 2536, zoneName = "Atal'Aman", poolName = "Open-Water"},
    },
    ["Restored Songfish"] = {
        { zoneID = 2393, zoneName = "Silvermoon City", poolName = "Open-Water"},
        { zoneID = 2395, zoneName = "Eversong Woods", poolName = "Bloom Swarm, Bubbling Bloom, Sunwell Swarm"},
        { zoneID = 2413, zoneName = "Harandar", poolName = "Blossoming Torrent"},
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Open-Water"},
        { zoneID = 2505, zoneName = "The Gulf of Memory", poolName = "Open-Water"},
        { zoneID = 2536, zoneName = "Atal'Aman", poolName = "Open-Water"},
        { zoneID = 2565, zoneName = "Isle of Quel'Danas", poolName = "Open-Water"},
    },
    ["Shimmersiren"] = {
        { zoneID = 2395, zoneName = "Eversong Woods", poolName = "Viscous Void"},
        { zoneID = 2405, zoneName = "Voidstorm", poolName = "Oceanic Vortex"},
        { zoneID = 2413, zoneName = "Harandar", poolName = "Viscous Void"},
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Viscous Void"},
        { zoneID = 2536, zoneName = "Atal'Aman", poolName = "Open-Water"},
    },
    ["Sunwell Fish"] = {
        { zoneID = 2393, zoneName = "Silvermoon City", poolName = "Open-Water"},
        { zoneID = 2395, zoneName = "Eversong Woods", poolName = "Sunwell Swarm"},
        { zoneID = 2413, zoneName = "Harandar", poolName = "Blossoming Torrent"},
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Open-Water"},
        { zoneID = 2505, zoneName = "The Gulf of Memory", poolName = "Open-Water"},
        { zoneID = 2536, zoneName = "Atal'Aman", poolName = "Open-Water"},
        { zoneID = 2565, zoneName = "Isle of Quel'Danas", poolName = "Open-Water"},
    },
    ["Tender Lumifin"] = {
        { zoneID = 2393, zoneName = "Silvermoon City", poolName = "Open-Water"},
        { zoneID = 2395, zoneName = "Eversong Woods", poolName = "Open-Water"},
        { zoneID = 2413, zoneName = "Harandar", poolName = "Blossoming Torrent"},
        { zoneID = 2565, zoneName = "Isle of Quel'Danas", poolName = "Open-Water"},
    },
    ["Eversong Trout"] = {
        { zoneID = 2393, zoneName = "Silvermoon City", poolName = "Open-Water"},
        { zoneID = 2395, zoneName = "Eversong Woods", poolName = "Sunwell Swarm"},
        { zoneID = 2413, zoneName = "Harandar", poolName = "Bubbling Bloom"},
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Open-Water"},
        { zoneID = 2565, zoneName = "Isle of Quel'Danas", poolName = "Open-Water"},
    },
    ["Hollow Grouper"] = {        
        { zoneID = 2395, zoneName = "Eversong Woods", poolName = "Viscous Void"},
        { zoneID = 2405, zoneName = "Voidstorm", poolName = "Oceanic Vortex"},
        { zoneID = 2413, zoneName = "Harandar", poolName = "Viscous Void"},
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Viscous Void"},
        { zoneID = 2536, zoneName = "Atal'Aman", poolName = "Open-Water"},
    },
    ["Lucky Loa"] = {
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Obscured School, Surface Ripple"},
        { zoneID = 2535, zoneName = "Atal'Aman", poolName = "Open-Water"},
        { zoneID = 2536, zoneName = "Atal'Aman", poolName = "Open-Water"},
    },
    ["Null Voidfish"] = {
        { zoneID = 2395, zoneName = "Eversong Woods", poolName = "Viscous Void"},
        { zoneID = 2405, zoneName = "Voidstorm", poolName = "Oceanic Vortex"},
        { zoneID = 2413, zoneName = "Harandar", poolName = "Viscous Void"},
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Viscous Void"},
        { zoneID = 2536, zoneName = "Atal'Aman", poolName = "Open-Water"},
    },
    ["Ominous Octopus"] = {
        { zoneID = 2395, zoneName = "Eversong Woods", poolName = "Viscous Void"},
        { zoneID = 2405, zoneName = "Voidstorm", poolName = "Oceanic Vortex"},
        { zoneID = 2413, zoneName = "Harandar", poolName = "Viscous Void"},
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Viscous Void"},
        { zoneID = 2536, zoneName = "Atal'Aman", poolName = "Open-Water"},
    },
    ["Twisted Tetra"] = {
        { zoneID = 2413, zoneName = "Harandar", poolName = "Lashing Waves"},
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Obscured School"},
        { zoneID = 2535, zoneName = "Atal'Aman", poolName = "Open-Water"},
        { zoneID = 2536, zoneName = "Atal'Aman", poolName = "Open-Water"},
        { zoneID = 2565, zoneName = "Isle of Quel'Danas", poolName = "Open-Water"},
    },
    ["Warping Wise"] = {
        { zoneID = 2395, zoneName = "Eversong Woods", poolName = "Viscous Void"},
        { zoneID = 2405, zoneName = "Voidstorm", poolName = "Oceanic Vortex"},
        { zoneID = 2413, zoneName = "Harandar", poolName = "Viscous Void"},
        { zoneID = 2437, zoneName = "Zul'Aman", poolName = "Viscous Void"},
        { zoneID = 2536, zoneName = "Atal'Aman", poolName = "Open-Water"},
    }
}